# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-15 00:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('1', 'Week 1'), ('2', 'Week 2'), ('3', 'Week 3'), ('4', 'Week 4'), ('5', 'Week 5'), ('6', 'Week 6'), ('7', 'Week 7'), ('8', 'Week 8'), ('9', 'Week 9'), ('10', 'Week 10'), ('11', 'Week 11'), ('12', 'Week 12'), ('13', 'Week 13'), ('14', 'Week 14'), ('15', 'Week 15'), ('16', 'Week 16'), ('17', 'Week 17'), ('18', 'Wild Card'), ('19', 'Divisional Round'), ('20', 'Conference Championship'), ('21', 'Super Bowl')], default='1', max_length=2)),
                ('qb_position', models.CharField(default='QB', max_length=2)),
                ('qb_first_name', models.CharField(max_length=20)),
                ('qb_last_name', models.CharField(max_length=20)),
                ('qb_team', models.CharField(choices=[('ARI', 'Arizona Cardinals'), ('ATL', 'Atlanta Falcons'), ('BAL', 'Baltimore Ravens'), ('BUF', 'Buffalo Bills'), ('CAR', 'Carolina Panthers'), ('CHI', 'Chicago Bears'), ('CIN', 'Cincinati Bengals'), ('CLE', 'Cleveland Browns'), ('DAL', 'Dallas Cowboys'), ('DEN', 'Denver Broncos'), ('DET', 'Detroit Lions'), ('GB', 'Green Bay Packers'), ('HOU', 'Houston Texans'), ('IND', 'Indianapolis Colts'), ('JAX', 'Jacksonville Jaguars'), ('KC', 'Kansas City Chiefs'), ('LA', 'Los Angeles Rams'), ('MIA', 'Miami Dolphins'), ('MINN', 'Minnesota Vikings'), ('NO', 'New Orleans Saints'), ('NE', 'New England Patriots'), ('NYG', 'New York Giants'), ('NYJ', 'New York Jets'), ('OAK', 'Oakland Raiders'), ('PHI', 'Philidelphia Eagles'), ('PIT', 'Pittsburgh Steelers'), ('SD', 'San Diego Chargers'), ('SF', 'San Fransico 49ers'), ('SEA', 'Seattle Seahawks'), ('TB', 'Tampa Bay Buccaneers'), ('TEN', 'Tennessee Titans'), ('WASH', 'Washington Redskins')], default='ARI', max_length=4)),
                ('rb1_position', models.CharField(default='RB', max_length=2)),
                ('rb1_first_name', models.CharField(max_length=20)),
                ('rb1_last_name', models.CharField(max_length=20)),
                ('rb1_team', models.CharField(choices=[('ARI', 'Arizona Cardinals'), ('ATL', 'Atlanta Falcons'), ('BAL', 'Baltimore Ravens'), ('BUF', 'Buffalo Bills'), ('CAR', 'Carolina Panthers'), ('CHI', 'Chicago Bears'), ('CIN', 'Cincinati Bengals'), ('CLE', 'Cleveland Browns'), ('DAL', 'Dallas Cowboys'), ('DEN', 'Denver Broncos'), ('DET', 'Detroit Lions'), ('GB', 'Green Bay Packers'), ('HOU', 'Houston Texans'), ('IND', 'Indianapolis Colts'), ('JAX', 'Jacksonville Jaguars'), ('KC', 'Kansas City Chiefs'), ('LA', 'Los Angeles Rams'), ('MIA', 'Miami Dolphins'), ('MINN', 'Minnesota Vikings'), ('NO', 'New Orleans Saints'), ('NE', 'New England Patriots'), ('NYG', 'New York Giants'), ('NYJ', 'New York Jets'), ('OAK', 'Oakland Raiders'), ('PHI', 'Philidelphia Eagles'), ('PIT', 'Pittsburgh Steelers'), ('SD', 'San Diego Chargers'), ('SF', 'San Fransico 49ers'), ('SEA', 'Seattle Seahawks'), ('TB', 'Tampa Bay Buccaneers'), ('TEN', 'Tennessee Titans'), ('WASH', 'Washington Redskins')], default='ARI', max_length=4)),
                ('rb2_position', models.CharField(default='RB', max_length=2)),
                ('rb2_first_name', models.CharField(max_length=20)),
                ('rb2_last_name', models.CharField(max_length=20)),
                ('rb2_team', models.CharField(choices=[('ARI', 'Arizona Cardinals'), ('ATL', 'Atlanta Falcons'), ('BAL', 'Baltimore Ravens'), ('BUF', 'Buffalo Bills'), ('CAR', 'Carolina Panthers'), ('CHI', 'Chicago Bears'), ('CIN', 'Cincinati Bengals'), ('CLE', 'Cleveland Browns'), ('DAL', 'Dallas Cowboys'), ('DEN', 'Denver Broncos'), ('DET', 'Detroit Lions'), ('GB', 'Green Bay Packers'), ('HOU', 'Houston Texans'), ('IND', 'Indianapolis Colts'), ('JAX', 'Jacksonville Jaguars'), ('KC', 'Kansas City Chiefs'), ('LA', 'Los Angeles Rams'), ('MIA', 'Miami Dolphins'), ('MINN', 'Minnesota Vikings'), ('NO', 'New Orleans Saints'), ('NE', 'New England Patriots'), ('NYG', 'New York Giants'), ('NYJ', 'New York Jets'), ('OAK', 'Oakland Raiders'), ('PHI', 'Philidelphia Eagles'), ('PIT', 'Pittsburgh Steelers'), ('SD', 'San Diego Chargers'), ('SF', 'San Fransico 49ers'), ('SEA', 'Seattle Seahawks'), ('TB', 'Tampa Bay Buccaneers'), ('TEN', 'Tennessee Titans'), ('WASH', 'Washington Redskins')], default='ARI', max_length=4)),
                ('wr1_position', models.CharField(default='WR', max_length=2)),
                ('wr1_first_name', models.CharField(max_length=20)),
                ('wr1_last_name', models.CharField(max_length=20)),
                ('wr1_team', models.CharField(choices=[('ARI', 'Arizona Cardinals'), ('ATL', 'Atlanta Falcons'), ('BAL', 'Baltimore Ravens'), ('BUF', 'Buffalo Bills'), ('CAR', 'Carolina Panthers'), ('CHI', 'Chicago Bears'), ('CIN', 'Cincinati Bengals'), ('CLE', 'Cleveland Browns'), ('DAL', 'Dallas Cowboys'), ('DEN', 'Denver Broncos'), ('DET', 'Detroit Lions'), ('GB', 'Green Bay Packers'), ('HOU', 'Houston Texans'), ('IND', 'Indianapolis Colts'), ('JAX', 'Jacksonville Jaguars'), ('KC', 'Kansas City Chiefs'), ('LA', 'Los Angeles Rams'), ('MIA', 'Miami Dolphins'), ('MINN', 'Minnesota Vikings'), ('NO', 'New Orleans Saints'), ('NE', 'New England Patriots'), ('NYG', 'New York Giants'), ('NYJ', 'New York Jets'), ('OAK', 'Oakland Raiders'), ('PHI', 'Philidelphia Eagles'), ('PIT', 'Pittsburgh Steelers'), ('SD', 'San Diego Chargers'), ('SF', 'San Fransico 49ers'), ('SEA', 'Seattle Seahawks'), ('TB', 'Tampa Bay Buccaneers'), ('TEN', 'Tennessee Titans'), ('WASH', 'Washington Redskins')], default='ARI', max_length=4)),
                ('wr2_position', models.CharField(default='WR', max_length=2)),
                ('wr2_first_name', models.CharField(max_length=20)),
                ('wr2_last_name', models.CharField(max_length=20)),
                ('wr2_team', models.CharField(choices=[('ARI', 'Arizona Cardinals'), ('ATL', 'Atlanta Falcons'), ('BAL', 'Baltimore Ravens'), ('BUF', 'Buffalo Bills'), ('CAR', 'Carolina Panthers'), ('CHI', 'Chicago Bears'), ('CIN', 'Cincinati Bengals'), ('CLE', 'Cleveland Browns'), ('DAL', 'Dallas Cowboys'), ('DEN', 'Denver Broncos'), ('DET', 'Detroit Lions'), ('GB', 'Green Bay Packers'), ('HOU', 'Houston Texans'), ('IND', 'Indianapolis Colts'), ('JAX', 'Jacksonville Jaguars'), ('KC', 'Kansas City Chiefs'), ('LA', 'Los Angeles Rams'), ('MIA', 'Miami Dolphins'), ('MINN', 'Minnesota Vikings'), ('NO', 'New Orleans Saints'), ('NE', 'New England Patriots'), ('NYG', 'New York Giants'), ('NYJ', 'New York Jets'), ('OAK', 'Oakland Raiders'), ('PHI', 'Philidelphia Eagles'), ('PIT', 'Pittsburgh Steelers'), ('SD', 'San Diego Chargers'), ('SF', 'San Fransico 49ers'), ('SEA', 'Seattle Seahawks'), ('TB', 'Tampa Bay Buccaneers'), ('TEN', 'Tennessee Titans'), ('WASH', 'Washington Redskins')], default='ARI', max_length=4)),
                ('te_position', models.CharField(default='TE', max_length=2)),
                ('te_first_name', models.CharField(max_length=20)),
                ('te_last_name', models.CharField(max_length=20)),
                ('te_team', models.CharField(choices=[('ARI', 'Arizona Cardinals'), ('ATL', 'Atlanta Falcons'), ('BAL', 'Baltimore Ravens'), ('BUF', 'Buffalo Bills'), ('CAR', 'Carolina Panthers'), ('CHI', 'Chicago Bears'), ('CIN', 'Cincinati Bengals'), ('CLE', 'Cleveland Browns'), ('DAL', 'Dallas Cowboys'), ('DEN', 'Denver Broncos'), ('DET', 'Detroit Lions'), ('GB', 'Green Bay Packers'), ('HOU', 'Houston Texans'), ('IND', 'Indianapolis Colts'), ('JAX', 'Jacksonville Jaguars'), ('KC', 'Kansas City Chiefs'), ('LA', 'Los Angeles Rams'), ('MIA', 'Miami Dolphins'), ('MINN', 'Minnesota Vikings'), ('NO', 'New Orleans Saints'), ('NE', 'New England Patriots'), ('NYG', 'New York Giants'), ('NYJ', 'New York Jets'), ('OAK', 'Oakland Raiders'), ('PHI', 'Philidelphia Eagles'), ('PIT', 'Pittsburgh Steelers'), ('SD', 'San Diego Chargers'), ('SF', 'San Fransico 49ers'), ('SEA', 'Seattle Seahawks'), ('TB', 'Tampa Bay Buccaneers'), ('TEN', 'Tennessee Titans'), ('WASH', 'Washington Redskins')], default='ARI', max_length=4)),
                ('k_position', models.CharField(default='K', max_length=2)),
                ('k_first_name', models.CharField(max_length=20)),
                ('k_last_name', models.CharField(max_length=20)),
                ('k_team', models.CharField(choices=[('ARI', 'Arizona Cardinals'), ('ATL', 'Atlanta Falcons'), ('BAL', 'Baltimore Ravens'), ('BUF', 'Buffalo Bills'), ('CAR', 'Carolina Panthers'), ('CHI', 'Chicago Bears'), ('CIN', 'Cincinati Bengals'), ('CLE', 'Cleveland Browns'), ('DAL', 'Dallas Cowboys'), ('DEN', 'Denver Broncos'), ('DET', 'Detroit Lions'), ('GB', 'Green Bay Packers'), ('HOU', 'Houston Texans'), ('IND', 'Indianapolis Colts'), ('JAX', 'Jacksonville Jaguars'), ('KC', 'Kansas City Chiefs'), ('LA', 'Los Angeles Rams'), ('MIA', 'Miami Dolphins'), ('MINN', 'Minnesota Vikings'), ('NO', 'New Orleans Saints'), ('NE', 'New England Patriots'), ('NYG', 'New York Giants'), ('NYJ', 'New York Jets'), ('OAK', 'Oakland Raiders'), ('PHI', 'Philidelphia Eagles'), ('PIT', 'Pittsburgh Steelers'), ('SD', 'San Diego Chargers'), ('SF', 'San Fransico 49ers'), ('SEA', 'Seattle Seahawks'), ('TB', 'Tampa Bay Buccaneers'), ('TEN', 'Tennessee Titans'), ('WASH', 'Washington Redskins')], default='ARI', max_length=4)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('K', 'Kicker')], default='QB', max_length=2)),
                ('team', models.CharField(choices=[('ARI', 'Arizona Cardinals'), ('ATL', 'Atlanta Falcons'), ('BAL', 'Baltimore Ravens'), ('BUF', 'Buffalo Bills'), ('CAR', 'Carolina Panthers'), ('CHI', 'Chicago Bears'), ('CIN', 'Cincinati Bengals'), ('CLE', 'Cleveland Browns'), ('DAL', 'Dallas Cowboys'), ('DEN', 'Denver Broncos'), ('DET', 'Detroit Lions'), ('GB', 'Green Bay Packers'), ('HOU', 'Houston Texans'), ('IND', 'Indianapolis Colts'), ('JAX', 'Jacksonville Jaguars'), ('KC', 'Kansas City Chiefs'), ('LA', 'Los Angeles Rams'), ('MIA', 'Miami Dolphins'), ('MINN', 'Minnesota Vikings'), ('NO', 'New Orleans Saints'), ('NE', 'New England Patriots'), ('NYG', 'New York Giants'), ('NYJ', 'New York Jets'), ('OAK', 'Oakland Raiders'), ('PHI', 'Philidelphia Eagles'), ('PIT', 'Pittsburgh Steelers'), ('SD', 'San Diego Chargers'), ('SF', 'San Fransico 49ers'), ('SEA', 'Seattle Seahawks'), ('TB', 'Tampa Bay Buccaneers'), ('TEN', 'Tennessee Titans'), ('WASH', 'Washington Redskins')], default='ARI', max_length=4)),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fnfl.Lineup')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tds', models.IntegerField(default=0)),
                ('pass_yds', models.IntegerField(default=0)),
                ('ints', models.IntegerField(default=0)),
                ('rush_yds', models.IntegerField(default=0)),
                ('rec_yds', models.IntegerField(default=0)),
                ('ret_tds', models.IntegerField(default=0)),
                ('two_pts', models.IntegerField(default=0)),
                ('fgs', models.IntegerField(default=0)),
                ('xps', models.IntegerField(default=0)),
                ('lineup_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fnfl.Lineup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fnfl.Player')),
            ],
        ),
    ]
