# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 22:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=50)),
                ('qb', models.CharField(max_length=50)),
                ('rb1', models.CharField(max_length=50)),
                ('rb2', models.CharField(max_length=50)),
                ('wr1', models.CharField(max_length=50)),
                ('wr2', models.CharField(max_length=50)),
                ('te', models.CharField(max_length=50)),
                ('k', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('K', 'Kicker')], default='QB', max_length=2)),
                ('team', models.CharField(choices=[('DAL', 'Dallas Cowboys'), ('WASH', 'Washington Redskins'), ('NYG', 'New York Giants'), ('PHI', 'Philidelphia Eagles'), ('ARI', 'Arizona Cardinals'), ('LA', 'Los Angeles Rams'), ('SF', 'San Fransico 49ers'), ('SEA', 'Seattle Seahawks'), ('CHI', 'Chicago Bears'), ('DET', 'Detroit Lions'), ('GB', 'Green Bay Packers'), ('MINN', 'Minnesota Vikings'), ('ATL', 'Atlanta Falcons'), ('CAR', 'Carolina Panthers'), ('NO', 'New Orleans Saints'), ('TB', 'Tampa Bay Buccaneers'), ('BUF', 'Buffalo Bills'), ('MIA', 'Miami Dolphins'), ('NE', 'New England Patriots'), ('NYJ', 'New York Jets'), ('DEN', 'Denver Broncos'), ('KC', 'Kansas City Chiefs'), ('OAK', 'Oakland Raiders'), ('SD', 'San Diego Chargers'), ('BAL', 'Baltimore Ravens'), ('CIN', 'Cincinati Bengals'), ('CLE', 'Cleveland Browns'), ('PIT', 'Pittsburgh Steelers'), ('HOU', 'Houston Texans'), ('IND', 'Indianapolis Colts'), ('JAX', 'Jacksonville Jaguars'), ('TEN', 'Tennessee Titans')], default='DAL', max_length=4)),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fnfl.Lineup')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tds', models.IntegerField(default=0)),
                ('pass_yds', models.IntegerField(default=0)),
                ('ints', models.IntegerField(default=0)),
                ('rush_yds', models.IntegerField(default=0)),
                ('rec_yds', models.IntegerField(default=0)),
                ('ret_tds', models.IntegerField(default=0)),
                ('two_pts', models.IntegerField(default=0)),
                ('fgs', models.IntegerField(default=0)),
                ('xps', models.IntegerField(default=0)),
                ('lineup_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fnfl.Lineup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fnfl.Player')),
            ],
        ),
    ]
