# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-04 12:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=50)),
                ('qb', models.CharField(max_length=50)),
                ('rb1', models.CharField(max_length=50)),
                ('rb2', models.CharField(max_length=50)),
                ('wr1', models.CharField(max_length=50)),
                ('wr2', models.CharField(max_length=50)),
                ('te', models.CharField(max_length=50)),
                ('k', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
