# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-11 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fnfl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('K', 'Kicker')], default='QB', max_length=2)),
                ('team', models.CharField(max_length=4)),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fnfl.Lineup')),
            ],
        ),
    ]
