# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnfl', '0002_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(choices=[('DAL', 'Dallas Cowboys'), ('WASH', 'Washington Redskins'), ('NYG', 'New York Giants'), ('PHI', 'Philidelphia Eagles'), ('ARI', 'Arizona Cardinals'), ('LA', 'Los Angeles Rams'), ('SF', 'San Fransico 49ers'), ('SEA', 'Seattle Seahawks'), ('CHI', 'Chicago Bears'), ('DET', 'Detroit Lions'), ('GB', 'Green Bay Packers'), ('MINN', 'Minnesota Vikings'), ('ATL', 'Atlanta Falcons'), ('CAR', 'Carolina Panthers'), ('NO', 'New Orleans Saints'), ('TB', 'Tampa Bay Buccaneers'), ('BUF', 'Buffalo Bills'), ('MIA', 'Miami Dolphins'), ('NE', 'New England Patriots'), ('NYJ', 'New York Jets'), ('DEN', 'Denver Broncos'), ('KC', 'Kansas City Chiefs'), ('OAK', 'Oakland Raiders'), ('SD', 'San Diego Chargers'), ('BAL', 'Baltimore Ravens'), ('CIN', 'Cincinati Bengals'), ('CLE', 'Clevland Browns'), ('PIT', 'Pittsburgh Steelers'), ('HOU', 'Houston Texans'), ('IND', 'Indianapolis Colts'), ('JAX', 'Jacksonville Jaguars'), ('TEN', 'Tennessee Titans')], default='DAL', max_length=4),
        ),
    ]
